# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EventApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EventApp
  #pod 'SwiftLint'

  pod 'MessageKit', :path => '../MessageKit'
  pod 'MessageInputBar', :git => 'https://github.com/MessageKit/MessageInputBar.git', :branch => 'master'
  pod 'FSCalendar'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftKeychainWrapper'

end
